# Generated by Django 4.1.7 on 2023-04-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(default='-', max_length=5),
            preserve_default=False,
        ),
    ]
